/** One entry on the Calendar view (`GET /calendar/events`) — a projection over
 * `Meeting`/`ClassSession` rows, not its own stored model. See
 * `apps/api/src/calendar/calendar.service.ts` for how it's assembled. */
export type CalendarEventKind = "MEETING" | "CLASS";

export interface CalendarEvent {
  /** Stable within one `from`/`to` request. For a plain meeting/class session
   * this is that row's own id; for an occurrence generated from a RECURRING
   * meeting it's `${meetingId}:${occurrenceStartIso}` since no per-occurrence
   * row exists in the database (see `isRecurringOccurrence`). */
  id: string;
  kind: CalendarEventKind;
  title: string;
  start: string;
  end: string | null;
  meetingId: string;
  meetingCode: string;
  meetingStatus: string;
  isOwner: boolean;
  /** True when this event was generated by projecting a RECURRING meeting's
   * single `scheduledStart`/`recurrenceFrequency`/`recurrenceUntil` forward
   * for display — joining it opens the one real, persistent meeting room
   * every occurrence shares, not a distinct room per date. */
  isRecurringOccurrence: boolean;
  classId?: string;
  className?: string;
}
